{% set name = "icepyx" %}
{% set version = "0.3.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/icepyx-{{ version }}.tar.gz
  sha256: 4c7ff229100e31359a30c6bda51e06fa6ffa6a12730b545cdfcf8bd8334de4dd

build:
  number: 0
  noarch: python
  script:
    - export SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}    # [unix]
    - set SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}    # [win]
    - {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python >=3.0
    - setuptools >=45
    - setuptools_scm >=3.4
    - toml
  run:
    - fiona
    - geopandas
    - h5py
    - matplotlib-base
    - numpy
    - python >=3.0
    - requests
    - shapely
    - xarray

test:
  imports:
    - icepyx
    - icepyx.core
  commands:
    - pip check
    - python -c "import icepyx; assert icepyx.__version__ != '0.0.0'"
  requires:
    - pip

about:
  home: https://github.com/icesat2py/icepyx.git
  summary: Python tools for obtaining and working with ICESat-2 data
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - lsetiawan
    - JessicaS11
    - weiji14
