{% set name = "icepyx" %}
{% set version = "1.1.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/icepyx-{{ version }}.tar.gz
  sha256: f49d58f202b3141af9552efbbc5670dc93e55e0afbb1a851a376640cd398c3a5

build:
  number: 0
  noarch: python
  script:
    - export SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}    # [unix]
    - set SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}    # [win]
    - {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python >=3.0
    - setuptools >=45
    - setuptools_scm >=3.4
    - toml
  run:
    - backoff
    - dask-core
    - dask-expr
    - datashader
    - earthaccess >=0.5.1
    - fiona
    - geopandas
    - h5netcdf
    - h5py
    - holoviews
    - hvplot
    - matplotlib-base
    - numpy
    - pandas
    - python >=3.0
    - requests
    - s3fs
    - shapely
    - xarray

test:
  imports:
    - icepyx
    - icepyx.core
    - icepyx.quest
  commands:
    - pip check
    - python -c "import icepyx; assert icepyx.__version__ != '0.0.0'"
  requires:
    - pip

about:
  home: https://github.com/icesat2py/icepyx
  doc_url: https://icepyx.readthedocs.io
  dev_url: https://github.com/icesat2py/icepyx
  summary: Python tools for obtaining and working with ICESat-2 data
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mfisher87
    - lsetiawan
    - JessicaS11
    - weiji14
