{% set python_min = "3.11" %}
{% set name = "icepyx" %}
{% set version = "2.0.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/icepyx-{{ version }}.tar.gz
  sha256: a2992d1991ae9e4896ea18e5eb19da82a21b753b02b4be66b4a37130077286b9

build:
  number: 0
  noarch: python
  script:
    - export SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}    # [unix]
    - set SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}    # [win]
    - {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools >=66
    - setuptools_scm
    - wheel
  run:
    - backoff
    - dask-core <2025.1.0
    - dask-expr
    - datashader
    - deprecated
    - earthaccess >=0.12.0
    - fiona
    - geopandas
    - h5netcdf
    - h5py
    - harmony-py >=1.0.0    
    - holoviews
    - hvplot
    - matplotlib-base
    - numpy
    - pandas
    - python >={{ python_min }}
    - requests
    - s3fs
    - shapely
    - xarray

test:
  imports:
    - icepyx
    - icepyx.core
    - icepyx.quest
  commands:
    - pip check
    - python -c "import icepyx; assert icepyx.__version__ != '0.0.0'"
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/icesat2py/icepyx
  doc_url: https://icepyx.readthedocs.io
  dev_url: https://github.com/icesat2py/icepyx
  summary: Python tools for obtaining and working with ICESat-2 data
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mfisher87
    - lsetiawan
    - JessicaS11
    - weiji14
