{% set name = "icepyx" %}
{% set version = "0.6.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/icepyx-{{ version }}.tar.gz
  sha256: a0365a67ae51ceb95b6c14cefca85704686ea8350496ecc521fcb74cdb36b308

build:
  number: 0
  noarch: python
  script:
    - export SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}    # [unix]
    - set SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}    # [win]
    - {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python >=3.0,<3.10
    - setuptools >=45
    - setuptools_scm >=3.4
    - toml
  run:
    - backoff
    - dask
    - datashader
    - fiona
    - geopandas
    - geoviews
    - h5netcdf
    - h5py
    - holoviews
    - hvplot
    - intake
    - intake-xarray
    - matplotlib-base
    - numpy
    - pandas
    - python >=3.0,<3.10
    - requests
    - shapely
    - tqdm
    - xarray

test:
  imports:
    - icepyx
    - icepyx.core
  commands:
    - pip check
    - python -c "import icepyx; assert icepyx.__version__ != '0.0.0'"
  requires:
    - pip

about:
  home: https://github.com/icesat2py/icepyx.git
  summary: Python tools for obtaining and working with ICESat-2 data
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - lsetiawan
    - JessicaS11
    - weiji14
