schema_version: 1

context:
  name: icepyx
  version: 2.0.2
  python_min: "3.11"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/icepyx-${{ version }}.tar.gz
  sha256: 92f848463cb0a1f0b3ac6090b9868a8d24e9efbd46f7694de2c159368eb12df6

build:
  number: 0
  noarch: python
  script:
    - if: unix
      then: export SETUPTOOLS_SCM_PRETEND_VERSION=${{ version }}
    - if: win
      then: set SETUPTOOLS_SCM_PRETEND_VERSION=${{ version }}
    - ${{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - setuptools >=66
    - setuptools_scm
    - wheel
  run:
    - backoff
    - dask-core
    - datashader
    - deprecated
    - earthaccess >=0.15.1
    - fiona
    - geopandas
    - h5netcdf
    - h5py
    - harmony-py >=1.0.0
    - holoviews >=1.13.0 # https://github.com/conda-forge/holoviews-feedstock/issues/120
    - hvplot
    - matplotlib-base
    - numpy
    - python >=${{ python_min }}
    - requests
    - s3fs
    - shapely
    - xarray
tests:
  - python:
      # imports:
      #   - icepyx
      #   - icepyx.core
      #   - icepyx.quest
      pip_check: true
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - dask <2026.1.2 # remove after ok with pyarrow as a required dep - github.com/dask/dask/pull/12258
        - pip
        - python ${{ python_min }}.*
    script:
      # Manual import checks to have dask<2026.1.2 constraint to avoid pyarrow dep
      - python -c "import icepyx"
      - python -c "import icepyx.core"
      - python -c "import icepyx.quest"
      - python -c "import icepyx; assert icepyx.__version__ != '0.0.0'"

about:
  summary: Python tools for obtaining and working with ICESat-2 data
  license: BSD-3-Clause
  license_file: LICENSE
  homepage: https://github.com/icesat2py/icepyx
  repository: https://github.com/icesat2py/icepyx
  documentation: https://icepyx.readthedocs.io

extra:
  recipe-maintainers:
    - JessicaS11
    - lsetiawan
    - mfisher87
    - weiji14
